---
title: Code
---

# Software 

*Also see our group's public repos on [GitHub](https://github.com/Yu-Group).*

* **[VeridicalFlow](https://github.com/Yu-Group/veridical-flow)**: Library for building stable, trustworthy data-science pipelines, PCS framework, [paper](https://www.pnas.org/content/117/8/3920), [docs](https://vflow.csinva.io/)

* **[simChef](https://github.com/Yu-Group/simChef)**: R package to facilitate PCS simulation studies, data science workflows

* **[imodels](https://github.com/csinva/imodels)**: Python package for interpretable machine learning models, FIGS, hierarchical shrinkage, MDI+, [FIGS paper](https://arxiv.org/abs/2201.11931), [hierarchical shrinkage paper](https://arxiv.org/abs/2202.00858), [MDI+ paper](https://arxiv.org/pdf/2307.01932)

* **[iRF](https://github.com/Yu-Group/iterative-Random-Forest)**: Iterative Random Forests, stable high-order interactions, PCS-guided, [paper](https://www.pnas.org/content/115/8/1943)

* **[Adaptive wavelets](https://github.com/Yu-Group/adaptive-wavelets)**: Adaptive interpretable wavelets and wavelet distillation, domain-agnostic, [paper](https://www.nature.com/articles/s41467-021-25759-1)

* **[COVID-19 severity prediction](https://github.com/Yu-Group/covid19-severity-prediction)**: Extensive COVID-19 data and forecasting for counties and hospitals, pandemic severity index, [paper](https://hdsr.mitpress.mit.edu/pub/p6isyf0g), [website](http://covidseverity.com/)

* **[Epistasis cardiac hypertrophy](https://github.com/Yu-Group/epistasis-cardiac-hypertrophy)**: Code for epistasis in genetic control of cardiac hypertrophy, PCS-guided, [preprint](https://www.biorxiv.org/content/10.1101/2021.12.22.473882v2), [PCS docs](https://yu-group.github.io/epistasis-cardiac-hypertrophy/)

* **[Molecular partner prediction](https://github.com/Yu-Group/molecular-partner-prediction)**: Predicting successful CME events using clathrin markers, cell biology

* **[sMPS2](https://github.com/Yu-Group/sMPS2)**: Simplified MyProstateScore2.0 for high-grade prostate cancer detection, clinical decision rules

* **[MS-analysis-NMF](https://github.com/Yu-Group/MS-analysis-NMF)**: Non-negative matrix factorization for deconvolving complex mass spectra, simulation study

* **[VDS book supplementary](https://github.com/Yu-Group/vds-book-supplementary)**: Supplementary materials for Veridical Data Science book, educational resources

* **[imodels-experiments](https://github.com/Yu-Group/imodels-experiments)**: Experimental interpretable models to accompany imodels package, rule-based models

* **[Yu Group website](https://github.com/Yu-Group/yugroup-website)**: Source code for the Yu Group website, web development

<!-- * **escv**: Selection of regularization for lasso, sparser interpretable models, first work related to PCS, [paper](https://www.tandfonline.com/doi/full/10.1080/10618600.2015.1092978)

* **stanmf**: Stability driven non-negative matrix factorization, PCS-guided dimensionality reduction, [paper](https://www.pnas.org/content/113/16/4290)

* **Causal inference**: X-learner for CATE prediction, staDISC for discovering stable subgroups, PCS-guided causal methods, [X-learner paper](https://arxiv.org/abs/1706.03461), [staDISC paper](https://arxiv.org/abs/2008.10109)

* **epiTree**: Learning epistatic polygenic phenotypes with boolean interactions, PCS inference, genetics, [paper](https://www.biorxiv.org/content/10.1101/2020.11.24.396846v1)

* **staDRIP**: Drug-response prediction using stability-driven methods, PCS-guided precision medicine, [paper](https://arxiv.org/abs/2011.06593)

* **Superheat**: R package for generating beautiful and customizable heatmaps, data visualization, [paper](https://www.tandfonline.com/doi/full/10.1080/10618600.2018.1473780)

* **SUFO**: Embedding space interpretations for mechanistic neural network understanding, transformers, [paper](https://arxiv.org/abs/2305.17588)

* **ACD**: Hierarchical interpretations for neural networks, TRIM, CDEP, SPEX for feature attribution and LLMs, [ACD paper](https://arxiv.org/abs/1806.05337), [CD-T paper](https://arxiv.org/abs/2407.00886)

* **MDI OOB**: Debiased random forest feature importance, statistical inference, [MDI+ paper](https://arxiv.org/abs/2307.01932), [MDI OOB paper](https://arxiv.org/abs/1906.10845)

* **MDL-Complexity**: Model complexity theory, information theory applications, [paper](https://jmlr.org/papers/v24/21-1133.html) -->