---
title: Papers
---

# Select Publications

*For the most up-to-date and complete list, see [Google Scholar](https://scholar.google.com/citations?user=xT19Jc0AAAAJ&hl=en) or [arXiv](https://arxiv.org/search/?query=bin+yu&searchtype=author).* 


## 2024

A. R. Hsu, Y. Cherapanamjeri, A. Y. Odisho, P. R. Carroll, B. Yu (2024). [Mechanistic Interpretation through Contextual Decomposition in Transformers.](https://arxiv.org/pdf/2407.00886)

Y. S. Tan, O. Ronen, T. Saarinen, B. Yu (2024). [The Computational Curse of Big Data for Bayesian Additive Regression Trees: a Hitting Time Analysis.](https://arxiv.org/pdf/2406.19958)

O. Ronen, A. I. Humayun, R. Balestriero, R. Baraniuk, B. Yu (2024). [ScaLES: Scalable Latent Exploration Score for Pre-Trained Generative Networks](https://arxiv.org/pdf/2406.09657)

S. Hayou, N. Ghosh, B. Yu (2024). [The Impact of Initialization on LoRA Fineuning Dynamics.](https://arxiv.org/pdf/2406.08447)

B. Yu (2024). [After Computational Reproducibility: Scientific Reproducibility and Trustworthy AI](https://hdsr.mitpress.mit.edu/pub/8qexde24/release/1) (Harvard Data Science Review)

S. Hayou, N. Ghosh, B. Yu (2024). [LoRA+: Efficient Low Rank Adaptation of Large Models](https://arxiv.org/abs/2402.12354) (Proc. ICML)

C. F. Elliott, J. Duncan, T. M. Tang, M. Behr, K. Kumbier, B. Yu (2024). [Designing a data science simulation with MERITS: a primer.](https://arxiv.org/abs/2403.08971)

Y. Chen, C. Singh, X. Liu, S. Zuo, B. Yu, H. He, J. Gao (2024). [Towards consistent natural-language explanations via explanation-consistent finetuning.](https://arxiv.org/abs/2401.13986)

N. R. Mallinar, A. Zane, S. Frei, B. Yu (2024). Minimum-Norm Interpolation Under Covariate Shift. (Proc. ICML) [arXiv](https://arxiv.org/pdf/2404.00522)

L. Sun, A. Agarwal, A. Kornblith, B. Yu, C. Xiong (2024). ED-Copilot: Reduce Emergency Department Wait Time with Language Model Diagnostic Assistance. (Proc. ICML) [arXiv](https://arxiv.org/abs/2402.13448)

## 2023

C. Singh*, A. R. Hsu*, R. Antonello, S. Jain, A. G. Huth, B. Yu, J. Gao (2023). [Explaining black box text modules in natural language with language models.](https://arxiv.org/abs/2305.09863)

Q. Zhang, C. Singh, L. Liu, X. Liu, B. Yu, J. Gao, T. Zhao (2023). [Tell your model where to attend: post-hoc attention steering for LLMs.](https://arxiv.org/abs/2311.02262)

Q. Wang*, T. M. Tang*, N. Youlton, C. S. Weldy, A. M. Kenney, O. Ronen, J. W. Hughes, E. T. Chin, S. C. Sutton, A. Agarwal, X. Li, M. Behr, K. Kumbier, C. S. Moravec, W. H. W. Tang, K. B. Margulies, T. P. Cappola, A. J. Buitte, R. Arnaout, J. B. Brown, J. R. Priest, V. N. Parikh, B. Yu*, E. Ashley* (2023). Epistasis regulates genetic control of cardiac hypertrophy. [medRxiv](https://www.medrxiv.org/content/10.1101/2023.11.06.23297858v1) ([Code](https://github.com/Yu-Group/epistasis-cardiac-hypertrophy)) ([PCS documentation](https://yu-group.github.io/epistasis-cardiac-hypertrophy/#overview))

R. Cahill, Y. Wang, R. P. Xian, A. J. Lee, H. Zeng, B. Yu, B. Tasic, R. Abbasi-Asl (2023). Unsupervised pattern discovery in spatial gene expression atlas reveals mouse brain regions beyond established ontology. [bioRxiv](https://www.biorxiv.org/content/10.1101/2023.03.10.531984v2) ([Code](https://github.com/abbasilab/osNMF))

E. Irajizad, A. Kenney, T. Tang, J. Vykoukal, R. Wu, E. Murage, J. B. Dennison, M. Sans, J. P. Long, M. Loftus, J. A. Chabot, M. D. Kluger, F. Kastrinos, L. Brais, A. Babic, K. Jajoo, L. S. Lee, T. E. Clancy, K. Ng, A. Bullock, J. M. Genkinger, A. Maitra, K. A. Do, B. Yu, B. W. Wolpin, S. Hanash, J. F. Fahrmann. (2023). [A blood-based metabolomic signature predictive of risk for pancreatic cancer](https://pubmed.ncbi.nlm.nih.gov/37729870/). Cell Reports Medicine 4(9): 101194. doi: 10.1016/j.xcrm.2023.101194. (PCS related) ([Editorial](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10518497/))

R. Dwivedi, C. Singh, B. Yu, M. Wainwright (2023). [Revisiting miniumu description length complexity in overparametrized models.](https://jmlr.org/papers/v24/21-1133.html) JMLR, 24(268): 1-59.

K. Wu, Y. Chen, W. Ha, B. Yu (2023). [Prominent roles of conditionally invariant components in domain adaptation: theory and algorithms.](https://arxiv.org/abs/2309.10301) JMLR (accepted). [https://arxiv.org/abs/2309.10301](https://arxiv.org/abs/2309.10301)

N. Ghosh, S. Frei, W. Ha, B. Yu (2023). The effect of SGD batch size on autoencoder learning: sparsity, sharpness and feature learning. [https://arxiv.org/abs/2308.03215](https://arxiv.org/abs/2308.03215)

R. Netzorg, J. Li, B. Yu (2024). Improving prototypical part networks with reward reweighting, reselection, and retraining. Proc. ICML. [https://arxiv.org/abs/2307.03887](https://arxiv.org/abs/2307.03887)

A. Agarwal, A. M. Kenny, Y. S. Tan, T. M. Tang, B. Yu (2023). MDI+: a flexible random forest-based feature importance framework. [https://arxiv.org/abs/2307.01932](https://arxiv.org/abs/2307.01932) (PCS related)

A. R. Hsu, Y. Cherapanamjeri, B. Park, T. Naumann, A. Odisho, and B. Yu (2023). Diagnosing transformers: illuminating feature space for clinical decison-making. Proc. ICLR. [https://arxiv.org/abs/2305.17588](https://arxiv.org/abs/2305.17588)

C. Singh, A. R. Hsu, R. Antonello, S. Jain, A. G. Huth, B. Yu and J. Gao (2023). Explaining black box text modules in natural language with language models. [https://arxiv.org/abs/2305.09863](https://arxiv.org/abs/2305.09863)

## 2022

D. Shen, P. Ding, J. Sekhon, B. Yu (2022). Same root different leaves: time series and cross-sectional methods in panel data. Econometrica (accepted). [https://arxiv.org/abs/2207.14481](https://arxiv.org/abs/2207.14481)

B. Park, X. Wu, B. Yu, A. Zhou (2022). [Offline evaluation in RL: soft stability weighting to combine fitted Q-learning and model-based methods.](https://openreview.net/forum?id=R3h3-bt0mq) NeurIPS 3rd Offline Reinforcement Learning Workshop.

Y. S. Tan, C. Singh, K. Nasseri, A. Agarwal, J. Duncan, O. Ronen, M. Epland, A. Kornblith, B. Yu (2022). [Fast interpretable greedy-tree sums (FIGS)](https://arxiv.org/abs/2201.11931). ([imodels 🔎](https://github.com/csinva/imodels) contains code for FIGS)

A. Agarwal, Y. S. Tan, O. Ronen, C. Singh, B. Yu (2022). [Hierarchical shrinkage: improving accuracy and interpretability of tree-based methods.](https://arxiv.org/abs/2202.00858) Proc. ICML ([imodels 🔎](https://github.com/csinva/imodels) contains code for hierarchical shrinkage (HS)).

B. Yu and C. Singh (2022). [Seven principles for rapid-response data science: lessons learned from covid-19 forecasting](https://projecteuclid.org/journals/statistical-science/volume-37/issue-2/Seven-Principles-for-Rapid-Response-Data-Science--Lessons-Learned/10.1214/22-STS855.full). Statistical Science, 36(2):266-269.

N. Ghosh, S. Mei, and B. Yu (2022). [The three stages of dynamics in high-dimensional kernel methods.](https://arxiv.org/abs/2111.07167) Proc. ICLR, 2022.

## 2021

Y. Tan, A. Agarwal, and B. Yu (2021). [A cautionary tale on fitting decision trees to data from additive models: generalization lower bounds.](https://arxiv.org/abs/2110.09626) Proc. AISTATS.

N. Altieri, B. Park, J. DeNero, A. Odisho, B. Yu. (2021). [Improving natural language information extraction from cancer pathology reports using transfer learning and zero-shot string similarity.](https://pubmed.ncbi.nlm.nih.gov/34604711/) JAMIA Open. 2021 Sept. 30 4(3).

C. Singh, W. Ha and B. Yu (2021). [Interpreting and Improving Deep-Learning Models with Reality Checks](https://arxiv.org/abs/2108.06847). To appear in "xxAI - Beyond Explainable AI" (eds. Holzinger et al.).

W. Ha, C. Singh, F. Lanusse, S. Upadhyayula, and B. Yu (2021). [Adaptive Wavelet Distillation from Neural Networks through Interpretation.](https://nips.cc/Conferences/2021/ScheduleMultitrack?event=28027) Proc. NeurIPS 2021. ([code](https://github.com/Yu-Group/adaptive-wavelets))

M. Behr, Y. Wang, X. Li, B. Yu (2022). [Provable Boolean Interaction Recovery from Tree Ensemble obtained via Random Forests.](https://arxiv.org/abs/2102.11800) PNAS. ([theory for iRF](https://www.pnas.org/doi/10.1073/pnas.1711236115), PCS-related)

N. Altieri, B. Park, M. Olson, J. DeNero, A. Odisho, B. Yu. (2021). Supervised line attention for tumor attribute classification from pathology reports: Higher performance with less data. Journal of Biomedical Informatics. 122 (2021) 103872. [arXiv version](https://arxiv.org/abs/2012.08113)

## 2020

M. Behr*, K. Kumbier*, A. Cordova-Palomera, M. Aguirre, E. Ashley, A. Butte, R. Arnaout, J. B. Brown, J. Preist*, B. Yu* (2020). [Learning epistatic polygenic phenotypes with Boolean interactions](https://www.biorxiv.org/content/10.1101/2020.11.24.396846v1) ([code](https://github.com/merlebehr/epiTree)) (PCS inference case study)

B. Norgeot*, G. Quer, B. K. Beaulieu-Jones, A. Torkamani, R. Dias, M. Gianfrancesco, R. Arnaout, I. S. Kohane, S. Saria, E. Topol, Z. Obermeyer, B. Yu & A. Butte* (2020). [Minimum information about clinical artificial intelligence modeling: the MI-CLAIM checklist](https://www.nature.com/articles/s41591-020-1041-y), Nature Medicine, 26, 1320–1324.

B. Yu (2020). [Stability expanded, in reality](https://hdsr.mitpress.mit.edu/pub/ekrhsui8/release/1). Harvard Data Science Review (PCS related)

B. Yu and R. Barter (2020). [Data science process: one culture.](https://www.tandfonline.com/doi/abs/10.1080/01621459.2020.1762615?journalCode=uasa20) JASA. (PCS related)

R. Dwivedi, Y. Tan, B. Park, M. Wei, K. Horgan, D. Madigan, B. Yu (2020). [Stable discovery of interpretable subgroups via calibration in causal studies (staDISC).](https://onlinelibrary.wiley.com/doi/10.1111/insr.12427) International Statistical Review ([code](https://github.com/Yu-Group/stadisc)) (PCS case study for causal inference)

X. Li, T. M. Tang, X. Wang, J. A. Kocher, B. Yu (2020). [A stability-driven protocol for drug response interpretable prediction (staDRIP)](https://arxiv.org/abs/2011.06593). NeurISP workshop on ML4H (Machine learning for Health) Extended Abstract.

A. Y. Odisho, B. Park, N. Altieri, J. DeNero, M. R Cooperberg, P. R .Carroll, B. Yu (2020). [Natural language processing systems for pathology parsing in limited data environments with uncertainty estimation.](https://academic.oup.com/jamiaopen/article/3/3/431/5922788) JAMIA Open.

L. Reiger, J. W. Murdoch, S. Singh, B. Yu (2020). [Interpretations are Useful: Penalizing Explanations to Align Neural Networks with Prior Knowledge](https://proceedings.icml.cc/static/paper_files/icml/2020/992-Paper.pdf). ICML Proceedings. ([code](https://github.com/laura-rieger/deep-explanation-penalization))

C. Singh, W. Ha, F. Lanusse, V. Boehm, J. Liu, B. Yu (2020). [Transformation Importance with Applications to Cosmology](https://arxiv.org/pdf/2003.01926.pdf) ICLR Workshop paper. ([code](https://github.com/csinva/transformation-importance))

N. Altieri, R. Barter, J. Duncan, R. Dwivedi, K. Kumbier, X. Li, R. Netzorg, B. Park, C. Singh*, Y. Tan, T.Tang, Y. Wang, C. Zhang, B. Yu*. (2020) [Curating a COVID-19 data repository and forecasting county-level death counts in the United States.](https://hdsr.mitpress.mit.edu/pub/p6isyf0g/release/1) Harvard Data Science Review ([code](https://github.com/Yu-Group/covid19-severity-prediction)) [7-day prediction results](https://covidseverity.com/) [Short talk video](https://www.stat.berkeley.edu/~binyu/ps/papers2020/RDSS20-yu.mp4)

B. Yu and K. Kumbier (2020) [Veridical data science](https://www.stat.berkeley.edu/~binyu/ps/papers2020/VDS20-YuKumbier.pdf) (PCS framework), PNAS. 117 (8), 3920-3929. [QnAs with Bin Yu.](https://www.stat.berkeley.edu/~binyu/ps/papers2020/VDS20-QnAsBinYu.pdf)

R. Dwivedi, N. Ho, K. Khamaru, M. J. Wainwright, M. I. Jordan and B. Yu (2020) [Sharp Analysis of Expectation-Maximization for Weakly Identifiable Mixture Models](https://arxiv.org/abs/1902.00194) AISTATS.

R. Dwivedi, N. Ho, K. Khamaru, M. J. Wainwright, M. I. Jordan and B. Yu (2020) [Singularity, Misspecification and the Convergence Rate of EM](https://arxiv.org/abs/1810.00828) Annals of Statistics.

Y. Chen, R. Dwivedi, M. J. Wainwright and B. Yu (2020) [Fast Mixing of Metropolized Hamiltonian Monte Carlo: Benefits of Multi-Step Gradients,](https://www.jmlr.org/papers/volume21/19-441/19-441.pdf) JMLR, [arXiv](https://arxiv.org/abs/1905.12247)

## 2019

R. Dwivedi, Y. Chen, M. J. Wainwright and B. Yu (2019) [Log-concave Sampling: Metropolis Hastings Algorithms are Fast](http://jmlr.org/papers/v20/19-306.html) JMLR.

D. Rothenhäusler and B. Yu (2019). [Incremental causal effects](https://arxiv.org/abs/1907.13258).

## 2018

Y. Chen, R. Dwivedi, M. J. Wainwright and B. Yu (2018) [Fast MCMC Algorithms on Polytopes](http://jmlr.org/papers/v19/18-158.html). JMLR . http://jmlr.org/papers/v19/18-158.html

Y. Chen, R. Dwivedi, M. J. Wainwright and B. Yu (2020) [Vaidya Walk: A Sampling Algorithm Based on Volumetric-Logarithmic Barrier](https://ieeexplore.ieee.org/abstract/document/8262876/) Allerton Conference 2017 https://ieeexplore.ieee.org/abstract/document/8262876/

W. J. Murdoch, C. Singh, K. Kumbier, R. Abbasi-Asl, and B. Yu* (2019) [Definitions, methods, and applications in interpretable machine learning.](https://www.stat.berkeley.edu/~binyu/ps/papers2020/iML19-Murdochetal.pdf) PNAS, 116 (44) 22071-22080.

W. J. Murdoch, C. Sign, and B. Yu (2019). [Hierarchical interpretations for neural network predictions.](https://openreview.net/pdf?id=SkEqro0ctQ) ICLR. ([code](https://github.com/csinva/hierarchical-dnn-interpretations))

Y. Wang, S. Wu and B. Yu (2020) [Unique Sharp Local Minimum in l1-minimization Complete Dictionary Learning.](https://jmlr.org/papers/volume21/19-169/19-169.pdf) JMLR. 21(63), pp. 1-52. Also at https://arxiv.org/abs/1902.08380

Y. Chen, R. Abbasi-Asl, A. Bloniarz, M. Oliver, B. Willmore, J. Gallant*, and B. Yu* (2018) [The DeepTune framework for modeling and characterizing neurons in visual cortex area V4](https://www.biorxiv.org/content/10.1101/465534v1) https://www.biorxiv.org/content/10.1101/465534v1

K. Kumbier, S. Sumanta, J. B. Brown, S. Celniker, and B. Yu* (2018) [Refining interaction search through signed iterative Random Forests.](https://arxiv.org/abs/1810.07287) [https://arxiv.org/abs/1810.0728](https://arxiv.org/abs/1810.0728) (an enhanced version of [iRF](https://www.pnas.org/doi/10.1073/pnas.1711236115), PCS related)

Y. Chen C. Jin, and B. Yu (2018) [Stability and Convergence Trade-off of Iterative Optimization Algorithms.](https://arxiv.org/abs/1804.01619) https://arxiv.org/abs/1804.01619

J. Murdoch, P. Liu, and B. Yu (2018) [Beyond word importance: contextual decomposition to extract interactions from LSTMs.](https://arxiv.org/abs/1801.05453) Proc. ICLR 2018. [https://arxiv.org/abs/1705.07356](https://arxiv.org/abs/1705.07356) ([code)](https://github.com/csinva/hierarchical-dnn-interpretations)

R. Diwivedi, Y. Chen, M. J. Wainwright, and B. Yu (2018) [Log-concave sampling: Metropolis-Hastings algorithms are fast!](https://arxiv.org/abs/1801.02309) https://arxiv.org/abs/1801.02309.

## 2017

Y. Chen, R. Dwivedi, M. J. Wainwright, and B. Yu (2017) [Fast MCMC sampling algorithms on polytopes](https://arxiv.org/abs/1710.08165) https://arxiv.org/abs/1710.08165.

B. Yu and K. Kumbier (2018) [Artificial Intelligence and Statistics](https://www.stat.berkeley.edu/~binyu/ps/papers2018/AI+Stat18.pdf) Frontiers of Information Technology and Electronic Engineering. 19(1), 6-9.

R. Abbasi-Asl and B. Yu (2017) [Structural Compression of Convolutional Neural Networks Based on Greedy Filter Pruning](https://arxiv.org/abs/1705.07356) https://arxiv.org/abs/1705.07356

R. Abbasi-Asl and B. Yu (2017) [Interpreting Convolutional Neural Networks Through Compression.](https://arxiv.org/abs/1711.02329) NIPS 2017. Symposium on Interpretable Machine Learning. (also https://arxiv.org/abs/1711.02329)

S. Kunzel, J. Sekhon, P. Bickel, and B. Yu* (2019) [Meta-learners for Estimating Heterogeneous Treatment Effects using Machine Learning,](https://www.pnas.org/content/116/10/4156) PNAS. 116 (10) 4156-4165.  https://arxiv.org/abs/1706.03461. [(code](https://github.com/soerenkuenzel/hte))

S. Basu, K. Kumbier, J. B. Brown*, and B. Yu* (2018) [iterative Random Forests to discover predictive and stable high-order interactions](https://www.stat.berkeley.edu/~binyu/ps/papers2018/iRF+SI18.pdf) PNAS, 115 (8), 1943-1948. ([code](https://github.com/Yu-Group/iterative-Random-Forest)) (PCS related)

S. Balakrishnan, M. Wainwright, B. Yu (2017) [Statistical Guarantees for the EM algorithm: from population to sample-based analysis.](https://www.stat.berkeley.edu/~binyu/ps/papers2017/EM17.pdf) Annals of Statistics, 45(1), 77 - 120.

R. Barter and B. Yu (2017) [Superheat: An R package for creating beautiful and extendable heatmaps for visualizing complex data](https://www.stat.berkeley.edu/~binyu/ps/papers2017/superheat17.pdf) JCGS (revised). https://github.com/rlbarter/superheat

H. Liu and B. Yu (2017) [Comments on: High-dimensional simultaneous inference with the bootstrap by Dezeure et al](https://www.stat.berkeley.edu/~binyu/ps/papers2017/LiuYu-test17.pdf) Test. 26: 740-750.

C. Carson et al (2016). [UC Berkeley Data Science Planning Initiative Faculty Advisory Board (FAB) Report.](https://www.stat.berkeley.edu/~binyu/ps/FAB2016.pdf) [FAB Report Executive Summary](https://www.stat.berkeley.edu/~binyu/ps/FAB-Summary2016.pdf)

S. Wu and B. Yu (2018). [Local identifiability of l1-minimization dictionary learning: a sufficient and almost necessary condition.](https://www.stat.berkeley.edu/~binyu/ps/papers2018/local-iden18.pdf) JMLR. 18, 1 - 56.

## 2016

K. Rohe, T. Qin and B. Yu* (2016). [Co-clustering directed graphs to discover asymmetries and directional communities.](http://www.pnas.org/content/113/45/12679.full.pdf?with-ds=yes) Proc. National Academy of Sciences (PNAS), 113(45), 12679 - 12684.

R. E. Kass, B. S. Caffo, M. Davidian, X. Meng, B. Yu, Nancy Reid* (2016). [Ten simple rules for effective statistical practice.](https://www.stat.berkeley.edu/~binyu/ps/papers2016/Ten-Simple-Rules.pdf) PLoS Comput. Biol., 12(6): e1004961. doi:10.1371/journal.pcbi.1004961

Siqi Wu, Antony Joseph, Ann S. Hammonds, Susan E. Celniker, Bin Yu*, and Erwin Frise* (2016). [Stability-driven nonnegative matrix factorization to interpret spatial gene expression and build local gene networks (with support information).](https://www.stat.berkeley.edu/~binyu/ps/papers2016/staNMF+SI.pdf) PNAS, pp. 4290 - 4295. ([code](https://github.com/yu-group/stanmf)) (PCS related)

A. Bloniarz, C. Wu, B. Yu, A. Talwalkar (2016). [Supervised neighborhoods for distributed nonparametric regression.](https://www.stat.berkeley.edu/~binyu/ps/papers2016/AISTATS16.pdf) Proc. of AISTATS, Barcelona, Spain.

## 2015

B. Yu (2015). [Data wisdom for data science.](http://www.odbms.org/2015/04/data-wisdom-for-data-science/) Operational Database Management Systems (ODBMS.ORG).

A. Bloniarz, H. Liu, C. Zhang, J. Sekhon, and B. Yu* (2015). [Lasso adjustments of treatment effect estimates in randomized experiments.](https://www.stat.berkeley.edu/~binyu/ps/papers2016/lasso-adj+SI16.pdf) PNAS. 113, 7383 - 7390.

P. Ma, M. W. Mahoney and B. Yu (2015). [A Statistical Perspective on Algorithmic Leveraging.](https://www.stat.berkeley.edu/~binyu/ps/papers2015/MaMahoneyYu2015.pdf) Journal of Machine Learning Research, 16, (2015), 861-911.

T. Moon, Y. Wang, Y. Liu, and B. Yu (2015). [Evaluation of a MISR-based high-resolution aerosol retrieval method using AERONET DRAGON campaign data.](http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7047927) IEEE Transactions on Geoscience and Remote Sensing, 53, 4328-4339.

## 2014

B. Yu (2014). [Let us own data science.](https://www.stat.berkeley.edu/~binyu/ps/papers2014/IMS-pres-address14-yu.pdf) [video](https://www.youtube.com/watch?v=92OjsYQJC1U) [IMS Bulletin](http://bulletin.imstat.org/2014/10/ims-presidential-address-let-us-own-data-science/) Institute of Mathematical Statistics (IMS) Presidental Address, ASC-IMS Joint Conference, Sydney, July, 2014.

G. Schiebinger, M. J. Wainwright and B. Yu (2014). [The geometry of kernelized spectral clustering.](http://arxiv.org/pdf/1404.7552v3.pdf) Annals of Statistics, 43, 819-846.

L. Miratrix, J. Jia, B. Yu, B. Gawalt, L. El Ghaoui, L. Barnesmoore, S. Clavier (2014). [Concise comparative summaries (CCS) of large text corpora with a human experiment.](https://www.stat.berkeley.edu/~binyu/ps/papers2014/CCS14.pdf) Ann. Applied Statist., 8, 499-529.

Y. Benjamini and B. Yu (2014). [The shuttle estimator for explainable variance in fMRI experiments.](https://www.stat.berkeley.edu/~binyu/ps/papers2012/BenjaminiY12.pdf) Annals of Applied Statistics, 7, 2007-2033.

D. Bean, P. Bickel, N. El Karoui and B. Yu (2014). [Optimal M-estimation in high-dimensional regression.](http://www.pnas.org/content/early/2013/08/08/1307845110.full.pdf+html) Proceedings of National Academy of Sciences, 110, 1456314568.

N. El Karoui, D. Bean, P. Bickel, C. Lim, and B. Yu (2014). [On robust regression with high-dimensional predictors.](http://www.pnas.org/content/early/2013/08/15/1307842110.full.pdf+html) Proceedings of National Academy of Sciences, 110, 1455714562.

P. Ma, M. W. Mahoney, B. Yu (2014). [A Statistical Perspective on Algorithmic Leveraging.](http://arxiv.org/abs/1306.5362) Proc. of International Conference on Machine Learning (ICML) (This conference paper contains some of preliminary results of the journal submission Ma et al. (2015))

A. Bloniarz, A. Talwalkar, J. Terhorst, M. Jordan, D. Patterson, B. Yu and Y. Song (2014). [Changepoint Analysis for Efficient Variant Calling.](https://www.stat.berkeley.edu/~binyu/ps/papers2014/Bloniarzetal14.pdf) Proc. of RECOMB 2014 (to appear).

Tao Shi (2013), [A conversation with Professor Bin Yu](http://www.yufamily.org/src/ShiTao_AnInterviewWithProfessorBinYu.php?xref=YuFamily_YuBin_interview_cn) International Chinese Statistical Association (ICSA) Bulletin, Vol 25, Issue 2, pp 85-98. ([Selected Parts in Statblogs](http://www.statsblogs.com/2013/07/09/a-conversation-with-professor-bin-yu/))

A. Joseph and B. Yu (2016). [The impact of regularization on spectral clustering.](https://www.stat.berkeley.edu/~binyu/ps/papers2016/reg-spectral16.pdf) Annals of Statistics. 4, 1765 - 1791.

C. Lim and B. Yu (2016). [Estimation Stability with Cross Validation (ESCV)](https://www.stat.berkeley.edu/~binyu/ps/papers2016/ESCV16.pdf) Journal of Computational and Graphical Statistics. 25, 464 - 492. (First paper towards PCS)

## 2013

A. S. Hammonds, C. A. Bristow, W. W. Fisher, R. Weiszmann, S. Wu, V. Hartenstein, M. Kellis, B. Yu, E. Frise, and S. E. Celniker (2013). [Spatial expression of transcription factors in Drosophila embryonic organ development.](https://www.stat.berkeley.edu/~binyu/ps/papers2013/Hammondsetal13.pdf) Genome Biology, 14(12), R140.

H. Liu and B. Yu (2013). [Asymptotic properties of Lasso+mLS and Lasso+Ridge in sparse high-dimensional linear regression.](https://www.stat.berkeley.edu/~binyu/ps/LassoOLSBootstrap13.pdf) Electron. J. Statist., 7, 312-3169.

J. Mairal and B. Yu (2013). [Supervised Feature Selection in Graphs with Path Coding Penalties and Network Flows.](http://jmlr.org/papers/v14/mairal13a.html) Journal of Machine Learning Research, 14, 2449-2485.

Y. Wang, X. Jiang, B. Yu, M. Jiang (2013). [A Hierarchical Bayesian Approach for Aerosol Retrieval Using MISR Data.](https://www.stat.berkeley.edu/~binyu/ps/papers2013/WangJiangYuJiang2013.pdf) J. American Statistical Association, 108, 483-493.

Y. He, J. Jia and B. Yu (2013). [Reversible MCMC on Markov equivalence classes of sparse directed acyclic graphs.](https://www.stat.berkeley.edu/~binyu/ps/papers2013/rev-MCMC13.pdf) Annals of Statistics, 41(4), 1742-1779.

B. Yu (2013). [Stability.](https://www.stat.berkeley.edu/~binyu/ps/papers2013/Yu13.pdf) Bernoulli, 19 (4), 1484-1500. (Invited paper for the Special Issue commemorating the 300th anniversary of the publication of Jakob Bernoullis Ars Conjectandi in 1712) (Begining of PCS)

J. Mairal and B. Yu (2013). Discussion on Grouping Strategies and Thresholding for High Dimensional Linear Models Journal of Statistical Planning and Inference, 143, 1451-1453.

C. Uhler, G. Raskutti, and P. Buhlmann and B. Yu (2013). [Geometry of faithfulness assumption in causal inference.](https://www.stat.berkeley.edu/~binyu/ps/papers2013/faithfulness13.pdf) Annals of Statistics, 41, 436-463.

L. Miratrix, J. Sehkon, and B. Yu (2013). [Adjusting Treatment Effect Estimates by Post-Stratification in Randomized Experiments.](https://www.stat.berkeley.edu/~binyu/ps/papers2013/post-stratification13.pdf) Journal of Royal Statistical Society, Series B, 75 (part 2), 369-396.

J. Jia, K. Rohe and B. Yu (2013) [The Lasso under Poisson-like Heteroscadecity.](https://www.stat.berkeley.edu/~binyu/ps/papers2013/lasso-poisson13.pdf) Statistica Sinica, 23, 99-118.

S. Negahban, P. Ravikumar, M. Wainwrigt, and B. Yu (2012) [A unified framework for high-dimensional analysis of M-estimators with decomposable regularizers.](https://www.stat.berkeley.edu/~binyu/ps/unified-797.pdf) Statistical Science, 27, 538-557.

G. Raskutti, M. Wainwrigt, and B. Yu (2012) [Minimax-optimal rates for sparse additive models over kernel classes via convex programming.](https://www.stat.berkeley.edu/~binyu/ps/papers2012/RaskuttiWY12.pdf) J. Machine Learning Research, 13, 389-427.

J. Mairal and B. Yu (2012). [Complexity analysis of the Lasso regularization path.](https://www.stat.berkeley.edu/~binyu/ps/Conferencepapers/MairalY12.pdf) Proc. of International Conference on Machine Learning (ICML).

## 2012

Yanfeng Gu, Shizhe Wang, Tao Shi, Yinghui Lu, Eugene E. Clothiaux, and Bin Yu (2012). [Multiple-kernel learning-based unmixing algorithm for estimation of cloud fractions with MODIS and CLOUDSAT data.](https://www.stat.berkeley.edu/~binyu/ps/Conferencepapers/GuWSLCY12.pdf) Proc. of IEEE International Geoscience and Remote Sensing Symposium (IGRSS).

## 2011

S. Nishimoto, A. T. Vu, T. Naselaris, Y. Benjamini, B. Yu, J. L. Gallant (2011). [Reconstructing visual experiences from brain activity evoked by natural movies.](https://www.stat.berkeley.edu/~binyu/ps/papers2011/NishimotoVNBYG11.pdf) Current Biology, 21(19), 1641-1646. [related videos](https://sites.google.com/site/gallantlabucb/publications/nishimoto-et-al-2011)

P. Ravikumar, M. Wainwright, G. Raskutti, B. Yu (2011). [High-dimensional covariance estimation by minimizing l1-penalized log-determinant divergence.](https://www.stat.berkeley.edu/~binyu/ps/papers2011/RavikumarWRY11.pdf) Electronic Journal of Statistics, 5, 935-980.

G. Raskutti, M. Wainwright, B. Yu (2011). [Minimax rates of estimation for high-dimensional linear regression over lq-balls.](https://www.stat.berkeley.edu/~binyu/ps/papers2011/RaskuttiWainwrightYu2011.pdf) IEEE Trans. Inform. Th., 57(10), 6976-6994.

K. Rohe, S. Chatterjee, and B. Yu (2011). [Spectral clustering and the high-dimensional Stochastic Block Model.](https://www.stat.berkeley.edu/~binyu/ps/papers2011/RoheCY11.pdf) Annals of Statistics, 39 (4), 1878-1915

V. Q. Vu, P. Ravikumar, T. Naselaris, K. N. Kay, J. L. Gallant, B. Yu* (2011). [Encoding and decoding V1 fMRI responses to natural images with sparse nonparametric models.](http://arxiv.org/pdf/1104.2805.pdf) Annals of Applied Statistics, 5, 1150-1182. (*First senior author as last author in biology tradition)

S. N. Pakzad, G. Rocha, and B. Yu (2011). Distributed modal identification by regularized auto regressive models. International Journal of Systems Science, 42, 1473-1489.

J. Yousafzai, P. Sollich, Z. Cvetkovic, and B. Yu (2011). [Combined Features and Kernel Design for Robust Phoneme Classification Using Support Vector Machines.](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5618550) IEEE Trans. Audio, Speech and Language Processing (to appear). 64.

X. Dai, J. Jia, B. Yu, El Ghaoui (2011) [SBA-term: Sparse Bilingual Association for terms.](http://www.eecs.berkeley.edu/~elghaoui/Pubs/icsc2011.pdf) Proc. International Conference on Semantic Computing.

B. Yu (2011). [Asymptotics and Coding Theory: One of the n - 1 Dimensions of Terry.](http://www.stat.berkeley.edu/~binyu/ps/Conferencepapers/Yu11.pdf) In Selected Works of Terry Speed (ed. S. Duoit), pp. 33-36, Springer.

## 2010

B. Yu (2010). [Remembering Leo.](https://www.stat.berkeley.edu/~binyu/ps/papers2010/Yu10.pdf) Annals of Applied Statistics, 4(4), 1657-1659.

J. Jia, Y. Benjamini, C. Lim, G. Raskutti, B. Yu (2010). [Comment on "Envelope models for parsimonious and efficient multivariate linear regression" by R. D. Cook, B. Li, and F. Chiaromonte.](https://www.stat.berkeley.edu/~binyu/ps/papers2010/JiaBLRY10.pdf) Statistica Sinica, 20, 961-967.

G. Raskutti, M. Wainwrigt, and B. Yu (2010) [Restricted Eigenvalue Properties for Correlated Gaussian Designs.](https://www.stat.berkeley.edu/~binyu/ps/papers2010/RaskuttiWY10.pdf) Journal of Machine Learning Research, 11, 2241-2259.

J. Jia and B. Yu (2010). [On model selection consistency of elastic net when p >>n.](https://www.stat.berkeley.edu/~binyu/ps/papers2010/JiaY10.pdf) Statistica Sinica, 10, 595-611.

P. Buhlmann and B. Yu (2010). [Boosting.](http://onlinelibrary.wiley.com/doi/10.1002/wics.55/abstract) Wiley Interdisciplinary Reviews: Computational Statistics, 2, 69-74.

L. Huang, J. Jia, B. Yu, B. Chun, P. Maniatis, M. Naik (2010). [Predicting Execution Time of Computer Programs Using Sparse Polynomial Regression.](https://www.stat.berkeley.edu/~binyu/ps/Conferencepapers/HuangJYCMN10.pdf) Proc. NIPS 2010.

Y. Han, F. Wu, J. Jia, Y. Zhuang and B. Yu (2010). [Multi-task Sparse Discriminant Analysis (MtSDA) with Overlapping Categories.](https://www.stat.berkeley.edu/~binyu/ps/Conferencepapers/HanWJZY10.pdf) Proc. of The 24th AAAI Conference on Artificial Intelligence, July 11-15, Atlanta, GA.

B. Gawalt, J. Jia, L. Miratrix, L. El Ghaoui, B. Yu, and S. Clavier (2010). [Discovering Word Associations in News Media via Feature Selection and Sparse Classification.](https://www.stat.berkeley.edu/~binyu/ps/Conferencepapers/GawaltJMGYC10.pdf) Proc. 11th ACM SIGMM International Confernece on Multimedia Information Retrieval (MIR).

## 2009

E. Anderes, B. Yu, V. Jovanovic, C. Moroney, M. Garay, A. Braverman, E. Clothiaux (2009) [Maximum Likelihood Estimation of Cloud Height from Multi-Angle Satellite Imagery.](https://www.stat.berkeley.edu/~binyu/ps/papers2009/AnderesYJMGBC09.pdf) Annals of Applied Statistics, 3, 902-921

T. Shi, M. Belkin, and B. Yu, (2009) [Data Spectroscopy: Eigenspace of Convolution Operator and Clustering](https://www.stat.berkeley.edu/~binyu/ps/shi.aos09.pdf) Annals of Statistics, 37 (6B), 3960-3984.

Vincent Q. Vu, Bin Yu, Robert E. Kass (2009) [Information In The Non-Stationary Case](https://www.stat.berkeley.edu/~binyu/ps/papers2009/VuYK09.pdf) Neural computation 21, 688-703.

N. Meinshausen and B. Yu (2009). [Lasso-type recovery of sparse representations for high-dimensional data.](https://www.stat.berkeley.edu/~binyu/ps/papers2009/MeinshausenY09.pdf) Annals of Statistics 37, 246-270.

P. Zhao, G. Rocha, and B. Yu (2009). [The composite absolute penalties family for grouped and hierarchical variable selection](https://www.stat.berkeley.edu/~binyu/ps/papers2009/ZhaoRY09.pdf) Annals of Statistics 37, 3468-3497. (An earlier version 'appeared as Grouped and hierarchical model selection through composite absolute penalties' by P. Zhao, G. Rocha and B. Yu, Department of Statistics, UC Berkeley, Tech. Rep 703.)

S. Negahban, P. Ravikumar, M. Wainwright, and B. Yu (2009). [A unified framework for high-dimensional analysis of $M$-estimators with decomposable regularizers](https://www.stat.berkeley.edu/~binyu/ps/Conferencepapers/NegahbanRWY09.pdf) Proc. NIPS, 2009. (This conference paper contains preliminary results of the journal submission Negahban et al. 2012).

G. Raskutti, M. Wainwright, B. Yu (2009) [High-dimensional regression under lq-ball sparsity: Optimal rates of convergence.](https://www.stat.berkeley.edu/~binyu/ps/Conferencepapers/RaskuttiWY09b.pdf) Proc. of Allerton Conference on Communication, Control, and Computing. (This conference paper contains some of preliminary results of the journal submission Ravikumar et al. 2011).

G. Raskutti, M. Wainwrigt, and B. Yu (2009) [Lower bounds on minimax rates for nonparametric regression with additive sparsity and smoothness.](https://www.stat.berkeley.edu/~binyu/ps/Conferencepapers/RaskuttiWY09a.pdf) Proc. NIPS, 2009. (This conference paper contains some of preliminary results of the journal submission Ravikumar et al. 2011).

## 2008

T. Shi, B. Yu, E. Clothiaux, and A. Braverman (2008). [Daytime Arctic Cloud Detection based on Multi-angle Satellite Data with Case Studies.](https://www.stat.berkeley.edu/~binyu/ps/jasa_resub.pdf) Journal of American Statistical Association. 103( 482), 584-593.

Peter Buhlmann and Bin Yu (2008) Invited discussion on "Evidence contrary to the statistical view of boosting (D. Mease and A. Wyner)". [(paper with discussion) ](https://www.stat.berkeley.edu/~binyu/ps/Mease08a_with_discussion.pdf) Journal of Machine Learning Research 9, 187-194.

P. Ravikumer, V. Vu, B. Yu, T. Naselaris, K. Kay, J. Gallant (2008). [Nonparametric sparse hiearchical models describe V1 fMRI responses to natural images](https://www.stat.berkeley.edu/~binyu/ps/rocha.pseudo.pdf) In Adavances in Neural Information Processing Systems (NIPS) 21, (2008). (This conference paper contains some preliminary results of journal paper Vu et al. (2011) on encoding models, but also contains an encoding model that is not in Vu et al. (2011). It does not contain decoding results.)

P. Ravikumar, G. Raskutti, M. Wainwright, B. Yu (2008) [Model selection in Gaussian graphical models: high-dimensional consistency of l1-regularized MLE.](https://www.stat.berkeley.edu/~binyu/ps/covsel.nips08.pdf) In Adavances in Neural Information Processing Systems (NIPS) 21, (2008).

T. Shi, M. Belkin, and B. Yu (2008). [Data spectroscopy: learning mixture models using eigenspaces of convolution operators.](https://www.stat.berkeley.edu/~binyu/ps/ICML08.pdf) Proc. of ICML 2008.

M. Ager, Z. Cvetkovic, P. Pollich, and B. Yu (2008). [Towards Robust Phoneme Classification Augmentation of PLP Models with Acoustic Waveforms.](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=7080758) Proceedings of EUSIPCO.

J. Yousafzai, Z. Cvetković, P. Pollich, and B. Yu (2008). [Combined PLP-Acoustic Waveform Classification for Robust Phoneme Recognition using Support Vector Machines.](http://www.eurasip.org/Proceedings/Eusipco/Eusipco2008/papers/1569105546.pdf) Proceedings of EUSIPCO.

## 2007

N. Meinshausen, G. Rocha, and B. Yu (2007). [A tale of three cousins: Lasso, L2Boosting, and Danzig](https://www.stat.berkeley.edu/~binyu/ps/aos.dis07.pdf) Annals of Statistics (invited discussion on Candes and Tao's Danzig Selector paper)

V. Vu, B. Yu, and R. Kass (2007). [Coverage Adjusted Entropy Estimation.](https://www.stat.berkeley.edu/~binyu/ps/entropy.sub.pdf) Statistics and Medicine, 26(21), 4039-4060.

B. Yu (2007). [Embracing Statistical Challenges in the Information Technology Age](https://www.stat.berkeley.edu/~binyu/ps/embracing.pdf) Technometrics (special issue on statistics and information technologies). vol. 49 (3), 237-248.

X. Jiang, Y. Liu, B. Yu and M. Jiang (2007). [Comparison of MISR aerosol optical thickness with AERONET measurements in Beijing metropolitan area.](https://www.stat.berkeley.edu/~binyu/ps/xin.pdf) Remote Sensing of Environment (Special Issue on Multi-angle Imaging SpectroRadiometer), vol. 107, pp. 45-53.

T. Shi, E. E. Clothiaux, B. Yu, A. J. Braverman, and G. N. Groff (2007). [Detection of Daytime Arctic Clouds using MISR and MODIS Data.](https://www.stat.berkeley.edu/~binyu/ps/misr-modis.pdf) Remote Sensing of Environment (Special Issue on Multi-angle Imaging SpectroRadiometer), vol. 107, pp. 172-184.

## 2006

Peng Zhao and Bin Yu (2006). [On Model Selection Consistency of Lasso.](https://www.stat.berkeley.edu/~binyu/ps/LassoConsi.pdf) J. Machine Learning Research, 7 (nov), 2541-2567.

B. Yu (2006). [Comments on: Monitoring networked applications with incremental quantile estimation by Chambers et al.](http://arxiv.org/pdf/0708.0338.pdf) Statist. Sci., 21, 483-485.

B. Yu (2006). [Comments on: Regularization in Statistics, by P. J. Bickel and B. Li.](https://www.stat.berkeley.edu/~binyu/ps/test06.pdf) Test, vol. 15 (2), pages 314-316.

P. Buhlmann and B. Yu (2006). [Sparse Boosing](https://www.stat.berkeley.edu/~binyu/ps/rev.pdf) Journal of Machine Learning Research ( 7 (June), 1001-1024). This is a shortened and more focused version of Buhlmann and Yu "Boosting, Model Selection, Lasso and Nonnegative Garotte" given below.

J. Gao, H. Suzuki, and B. Yu (2006). [Approximation Lasso Methods for Language Modeling.](https://www.stat.berkeley.edu/~binyu/ps/acl.06.pdf) Proceedings of the 21st International Conference on Computational Linguistics and 44th Annual Meeting of the ACL, pp. 225-232, Sydney.

## 2005

T. Shi and B. Yu (2005). [Binning in Gaussian Kernel Regularization.](https://www.stat.berkeley.edu/~binyu/ps/binning.final.pdf) Statistica Sinica (special issue on machine learning), 16, 541-567.

G. Liang, N. Taft, and B. Yu (2005). [A fast lightweight approach to origin-destination IP traffic estimation using partial measurements.](https://www.stat.berkeley.edu/~binyu/ps/pamtram.final.pdf) Tech Report 687, Statistics Department, UCB (accepted for Special Issue of IEEE-IT and ACM Networks on data networks, Jan. 2006)

Tong Zhang and B. Yu (2005). [Boosting with early stopping: convergence and consistency.](https://www.stat.berkeley.edu/~binyu/ps/zhang.final.ps) The Annals of Statistics. Vol. 33, 1538-1579.

Castro, M. Coates, G. Liang, R. Nowak, and B. Yu (2005) [Network tomography: recent developments.](http://nowak.ece.wisc.edu/StatSci04.pdf) Statistical Science, 19, 499-517.

C. D. Giurcaneanu and B. Yu (2005). [Efficient algorithms for discrete universal denoising for channels with memeory.](https://www.stat.berkeley.edu/~binyu/ps/isit05.pdf) Proceedings of International Symposium on Information Theory, Australia. (Also as Tech. Report 686, Statistics Department, UCB (Proc. ISIT, Sept. 2005))

## 2004

P. Zhao and B. Yu (2004). [Stagewise Lasso (old title: Boosted Lasso)](https://www.stat.berkeley.edu/~binyu/ps/StagewiseLasso.pdf) Journal of Machine Learning Research, 8, 2701-2726. (An earlier version appeared as Tech. Report #678, Statistics Department, UC Berkeley (December, 2004; revised in April, 2005)

D. J. Diner et al (2004). [PARAGON: A Systematic, Integrated Approach to Aerosol Observation and Modeling.](https://www.stat.berkeley.edu/~binyu/ps/paragon.pdf) American Meterological Society, Oct., 1491-1501.

P. Buhlmann and B. Yu (2004). [Discussion on three boosting papers by Jiang, Lugosi and Vayatis, and Zhang](https://www.stat.berkeley.edu/~binyu/ps/disc2.ps) Annals of Statistics. 32 (1): 96-101.

R. Jorsten and B. Yu (2004). [Compressing genomic and proteomic array images for statistical analyses.](https://www.stat.berkeley.edu/~binyu/ps/sig.chapter.ps) Invited chapter in a book on Genomic signal processing and statistics, edited by E. R. Dougherty, I. Shmulevich, J. Chen, and Z. J. Wang, pp. 341 - 366.

G. Liang, B. Yu, and N. Taft (2004). [Maximum entropy models: convergence rates and application in dynamic system monitoring.](http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=1365207&sortType%3Dasc_p_Sequence%26filter%3DAND%28p_IS_Number%3A29909%29%26pageNumber%3D4%26rowsPerPage%3D50) International Symposium on Information Theory, Chicago.

## 2003

R. Castro, M. Coates, G. Liang, R. Nowak, and B. Yu (2003). [Internet Tomography: Recent Developments](https://www.stat.berkeley.edu/~binyu/ps/cny.pdf) Statistical Science. Vol. 19(3), 499-517.

G. Liang and B. Yu (2003). [Maximum Pseudo Likelihood Estimation in Network Tomography.](https://www.stat.berkeley.edu/~binyu/ps/pseudo-ieee.ps) IEEE Trans. on Signal Processing (Special Issue on Data Networks). 51(8), 2043-2053

Rebecka Jornsten and Bin Yu (2003). [Simultaneous Gene Clustering and Subset Selection for Classification via MDL.](https://www.stat.berkeley.edu/~binyu/ps/bioinformatics.ps) Bioinformatics. 19(9): 1100-1109.

Peter Buhlmann and Bin Yu (2003). [Boosting with the L2 Loss: Regression and Classification.](https://www.stat.berkeley.edu/~binyu/ps/boostingl2.ps) J. Amer. Statist. Assoc. 98, 324-340.

R. Jornsten, W. Wang, B. Yu, and K. Ramchandran (2003). [Microarray image compression: SLOCO and the effects of information loss.](https://www.stat.berkeley.edu/~binyu/ps/spj.ps) Signal Processing Journal (Special Issue on Genomic Signal Processing). 83, 859-869.

G. Liang and B. Yu (2003). [Pseudo Likelihood Estimation in Network Tomography.](http://infocom2003.ieee-infocom.org/papers/51_03.PDF) Proceedings of of Infocom, San Francisco.

## 2002

Peter Buhlmann and Bin Yu (2002). [Analyzing Bagging.](https://www.stat.berkeley.edu/~binyu/ps/bagging.ps) Annals of Statistics vol. 30, 927-961.

R. Jornsten, M. Hansen, and B. Yu (2002). Adaptive Minimum Description Length (MDL) criteria with applications to microarray data. In Advances in Minimum Description Length: Theory and Applications, edited by P. Grunwald, I.J. Myung and M.A. Pitt. The MIT Press, pp. 295-321.

Mark Hansen and Bin Yu (2002). [Minimum Description Length Model Selection Criteria for Generalized Linear Models.](https://www.stat.berkeley.edu/~binyu/ps/mdl_glm.ps){\em Science and Statistics: Festschrift for Terry Speed}, IMS Lecture Notes -- Monograph Series, Vol. 40.

Rebecka Jornsten, and Bin Yu (2002). [Multiterminal Estimation: Extensions and a Geometric interpretation.](https://www.stat.berkeley.edu/~binyu/ps/isit02.ps) Proceedings of International Symposium on Information Theory (ISIT), June, 2002.

Gerald Schuller, Bin Yu, Dawei Huang, and Bern Edler (2002). [Perceptual Audio Coding using Pre- and Poster- Filters and Lossless Compression.](https://www.stat.berkeley.edu/~binyu/ps/coding.ps) IEEE Trans. Speech and Audio Processing. Vol. 10 (6), 379-390

Mark Coates, Alfred Hero, Robert Nowak, and Bin Yu (2002). [Internet Tomography.](https://www.stat.berkeley.edu/~binyu/ps/spmag.ps) Signal Processing Magazine. vol. 19, No. 3 (May issue), 47-65.

## 2001

M. Hansen and B. Yu (2001). [Model selection and the principle of Minimum Description Length.](https://www.stat.berkeley.edu/~binyu/ps/mdl.ps) Journal of American Statistical Association. 96, 746-774.

## 2000

Jin Cao, Drew Davis, Scott Vander Wiel and Bin Yu (2000). [[ PDF ](https://www.stat.berkeley.edu/~binyu/Site/ps/net.pdf)| [Time-varying network tomography: router link data.](https://www.stat.berkeley.edu/~binyu/ps/net.ps) J. Amer. Statist. Assoc. vol. 95, 1063-1075.

Peter Buhlmann and Bin Yu (2000). [Discussion. Additive logistic regression: a statistical view of boosting, by Friedman, J., Hastie, T. and Tibshirani, R.](https://www.stat.berkeley.edu/~binyu/ps/disc.ps) Annals of Statistics. Vol. 28, 377-386

Mark Hansen and Bin Yu (2000). [Wavelet thresholding via MDL for natural images.](https://www.stat.berkeley.edu/~binyu/ps/lmdl.ps) IEEE Trans. Inform. Theory (Special Issue on Information Theoretic Imaging). vol. 46, 1778-1788.

Jorma Rissanen and Bin Yu (2000). [Coding and compression: a happy union of theory and practice.](https://www.stat.berkeley.edu/~binyu/ps/vig.ps) J. Amer. Statist. Assoc. (Year 2000 Commemorative Vignette on Engineering and Physical Sciences). vol. 95, 986-988.

Lei Li and Bin Yu (2000). [Iterated logarithm expansions of the pathwise code lengths for exponential families.](https://www.stat.berkeley.edu/~binyu/ps/pred.ps) IEEE Trans. Inform. Theory. vol. 46, 2683-2689.

G. Chang, B. Yu and M. Vetterli (2000). [Adaptive wavelet thresholding for image denoising and compression.](https://www.stat.berkeley.edu/~binyu/ps/jMDLQ.ps) IEEE Trans. Image Processing, vol. 9, 1532-1546.

G. Chang, B. Yu and M. Vetterli (2000). [Spatially adaptive wavelet thresholding based on context modeling for image denoising.](https://www.stat.berkeley.edu/~binyu/ps/spatThr.ps) IEEE Trans. Image Processing, vol. 9, 1522-1531.

G. Chang, B. Yu and M. Vetterli (2000). [Wavelet thresholding for multiple noisy image copies.](https://www.stat.berkeley.edu/~binyu/ps/mt.ps) IEEE Trans. Image Processing, vol. 9, 1631-1635.

## 1999

Y. Yoo, A. Ortega, and B. Yu (1999). [Image subband coding using context-based classification and adaptive quantization.](https://www.stat.berkeley.edu/~binyu/ps/yoo.ps) IEEE Trans. Image Processing, vol. 8, 1702-1215.

B. Yu, M. Ostland, P. Gong and R. Pu (1999). Penalized discriminant analysis of in situ hyperspectral data for conifer species recognition. IEEE Trans. Geoscience and Remote Sensing, in press.

## 1998

A. Barron, J. Rissanen, and B. Yu (1998). The Minimum Description Length principle in coding and modeling. (Special Commemorative Issue: Information Theory: 1948-1998) IEEE. Trans. Inform. Th., 44, 2743-2760. Reprinted in Information 50 Years of Discovery, Theory: S. Verdu and S. McLaughlin (eds), IEEE Press , 1999.

B. Yu and P. Mykland (1998). Looking at Markov samplers through cusum path plots: a simple diagnostic idea. Statistics and Computing , 8, 275-286.

P. Gong, R. Pu and B. Yu (1998) Conifer species recognition: effects of data transformation and band width (in Chinese) Journal of Remote Sensing, 2(3), 211-217.

G. Chang, B. Yu and M. Vetterli (1998). [Spatially adaptive wavelet thresholding for image denoising.](http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=862630) Proceedings of IEEE International Conference on Image Processing, October, Chicago.

S. G. Chang, B. Yu, and M. Vetterli (1998). [Image denoising via lossy compression and wavelet thresholding.](http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=647985) Proceedings of International Conference on Image Processing. Santa Barbara, California, vol. 1, pp. 604-607.

M. Ostland and B. Yu (1997). [Exploring quasi Monte Carlo for marginal density approximation.](https://www.stat.berkeley.edu/~binyu/ps/quasiMC.pdf) Statistics and Computing, 7, 217-228.

P. Gong, R. Pu, and B. Yu (1997). Conifer species recognition with in Situ hyperspectral data. Remote Sensing of Environment, 62, 189-200.

B. Yu and T. P. Speed (1997). [Information and the clone mapping of chromosomes.](https://www.stat.berkeley.edu/~binyu/ps/clone.pdf) Ann. Statist. 25, 169-185.

## 1997

D. Nelson, T. Speed, and B. Yu (1997). The limits of random fingerprinting. Genomics, 40, 1-12.

B. Yu (1997). [Assouad, Fano, and Le Cam.](https://www.stat.berkeley.edu/~binyu/ps/LeCam.pdf) Festschrift for Lucien Le Cam . D. Pollard, E. Torgersen, and G. Yang (eds), pp. 423-435, Springer-Verlag.

## 1996

B. Yu (1996). Lower bounds on expected redundancy for nonparametric classes. IEEE Trans. on Information Theory, 42, 272-275.

Y. Yoo, A. Ortega, and B. Yu (1996). Adaptive quantization of image subbands with efficient overhead rate selection. In Proceedings of IEEE International Conference on Image Processing, Lausanne, Switzerland.

B. Yu (1996). [A Statistical analysis of adaptive scalar quantization based on quantized past data.](https://www.stat.berkeley.edu/~binyu/ps/quan.ps) In Proceedings of International Symposium on Information Theory and its Applications (ISITA96), Victoria, Canada.

## 1995

B. Yu (1995). Comment: Extracting more diagnostic information from a single run using cusum path plot. Statist. Sci., 10, 54-58.

J. Rissanen and B. Yu (1995). MDL learning. In Learning and Geometry: Computational Approaches, Progress in Computer Science and Applied Logic, 14, David Kueker and Carl Smith (eds), Birkhäuser, Boston, pp. 3-19.

P. Mykland, L. Tierney, and B. Yu (1995). Regeneration in Markov Chain samplers. J. Amer. Statist. Assoc., 90, 233-241.

## 1994

B. Yu (1994). Rates of convergence for empirical processes of stationary mixing sequences. Ann. Probab. 22, 94-116.

M. Arcones and B. Yu (1994). Central limit theorems for empirical and U-processes of stationary mixing sequences. J. Theor. Probab. 7, 47-71.

B. Yu (1994). Lower bound on the expected redundancy for classes of continuous Markov sources. In Statistical Decision Theory and Related Topics V, S. S. Gupta and J. O. Berger (eds), 453-466.

M. Arcones and B. Yu (1994). Limit theorems for empirical processes under dependence. In Proceedings in Chaos expansions, multiple Wiener integrals and their applications. 205-221.

A. R. Barron, Y. Yang and B. Yu (1994). Asymptotically optimal function estimation by minimum complexity criteria. In Proceedings of 1994 International Symposium on Information Theory, pp. 38, Trondheim, Norway.

## 1993

B. Yu and T. Speed (1993). A rate of convergence result for a universal D-semifaithful code. IEEE Trans. on Information Theory 39, 8813-820.

B. Yu (1993). Density estimation in the L∞ norm for dependent data with applications to the Gibbs sampler. Ann. Statist. 21, 711-735.

T. Speed and B. Yu (1993). Model selection and prediction: normal regression. J. Inst. Statist. Math. 45, 35-54.

## 1992

J. Rissanen, T. Speed and B. Yu (1992). Density estimation by stochastic complexity. IEEE Trans. on Information Theory, 38, 315-323.

B. Yu and T. Speed (1992) Data compression and histograms. Probability Theory and Related Fields, 92, 195-229.
