---
title: Research
---

# Research

In 2014, I was elected to the National Academy of Sciences based on my statistical and scientific contributions, as well as my broad vision of data science best described in my article [Veridical Data Science](https://www.pnas.org/content/117/8/3920), written together with my former student Karl Kumbier. In this work, I introduced a framework based on three principles: predictability, computability and stability (abbreviated to PCS). This framework helps guide practitioners who solve domain data problems with data science tools to be creative in their analysis and properly validate their findings. I have written a book on the Veridical Data Science framework together with my former student [Rebecca Barter](https://www.rebeccabarter.com/). The book is being published by the MIT Press in 2024 with a free on-line copy available soon.

In my research group, I cultivate a strongly interdisciplinary and collaborative culture, solving data problems across fields such as neuroscience, genomics, remote sensing, and precision medicine. Through these projects we have successfully [mapped a cell's destiny](https://newscenter.lbl.gov/2016/05/04/mapping-cells-destiny/) using spatial gene expression images of Drosophila embryos, we have characterized V4 neurons through [DeepTune](https://www.biorxiv.org/content/10.1101/465534v1) images, and we are currently seeking genomic markers of heart disease using UK Biobank data. Recently, my group and I have developed approaches for [predicting county-level COVID-19 death counts](https://covidseverity.com/) in an effort to support the non-profit, [Response4Life](https://response4life.org/), who are working towards distributing PPE across the country to those who need it most.

The Yu Group and I have also developed an array of statistical and machine learning methods inspired by our interdisciplinary projects, including [stability-driven nonnegative matrix factorization (staNMF)](https://github.com/Yu-Group/staNMF) for unsupervised learning, [iterative Random Forests (iRF)](https://github.com/Yu-Group/iterative-Random-Forest) and [signed iRF (s-iRF)](https://github.com/karlkumbier/iRF2.0) for discovering predictive and stable high-order (Boolean) interactions in supervised learning, [contextual decomposition (CD)](https://github.com/jamie-murdoch/ContextualDecomposition) and [aggregated contextual decomposition (ACD)](https://github.com/csinva/hierarchical-dnn-interpretations) for phrase or patch importance extraction from Deep Neural Networks (DNNs).

Research is supported in part by grants from NSF, NIH, the Weill Neurohub, and the Simons Foundation.

- [Yu Group at Berkeley](https://www.stat.berkeley.edu/~yugroup/) for current group members and current projects
- [Papers](https://binyu.stat.berkeley.edu/papers)
- [Code](https://www.stat.berkeley.edu/~yugroup/code.html)
- [Statistical Machine Learning at Berkeley](http://www.stat.berkeley.edu/~statlearning/)

