---
title: "Deep Learning and Machine Learning"
---

[Complete Paper List in Reverse Chronological Order](../papers.qmd)

## Selected Recent Papers in Deep Learning and Machine Learning

1. A. R. Hsu, Y. Cherapanamjeri, A. Y. Odisho, P. R. Carroll, B. Yu (2024). [Mechanistic Interpretation through Contexual Decomposition in Transformers.](https://arxiv.org/pdf/2407.00886) [https://arxiv.org/pdf/2407.00886](https://arxiv.org/pdf/2407.00886).
1. O. Ronen, A. I. Humayun, R. Balestriero, R. Baraniuk, B. Yu (2024). [ScaLES: Scalable Latent Exploration Score for Pre-Trained Generative Networks](https://arxiv.org/pdf/2406.09657). [https://arxiv.org/pdf/2406.09657](https://arxiv.org/pdf/2406.09657)
1. S. Hayou, N. Ghosh, B. Yu (2024). [The Impact of Initialization on LoRA Fineuning Dynamics.](https://arxiv.org/pdf/2406.08447) [https://arxiv.org/pdf/2406.08447](https://arxiv.org/pdf/2406.08447)
1. B. Yu (2024). [After Computational Reproducibility: Scientific Reproducibility and Trustworthy AI](https://hdsr.mitpress.mit.edu/pub/8qexde24/release/1) (discussion of Donoho's paper "Data Science at the Singularity") Harvard Data Science Review (HDSR).
1. N. R. Mallinar, A. Zane, S. Frei, B. Yu (2024). Minimum-Norm Interpolation Under Covariate Shift. Proc. ICML. [https://arxiv.org/pdf/2404.00522](https://arxiv.org/pdf/2404.00522)
1. L. Sun, A. Agarwal, A. Kornblith, B. Yu, C. Xiong (2024). ED-Copilot: Reduce Emergency Department Wait Time with Language Model Diagnostic Assistance. Proc. ICML. [https://arxiv.org/abs/2402.13448](https://arxiv.org/abs/2402.13448)
1. S. Hayou, N. Ghosh, B. Yu (2024). [LoRA+: Efficient Low Rank Adaptation of Large Models](https://arxiv.org/abs/2402.12354). Proc. ICML. [https://arxiv.org/abs/2402.12354](https://arxiv.org/abs/2402.12354)
1. N. Ghosh, S. Frei, W. Ha, B. Yu (2023). The effect of SGD batch size on autoencoder learning: sparsity, sharpness and feature learning. [https://arxiv.org/abs/2308.03215](https://arxiv.org/abs/2308.03215)
1. A. R. Hsu, Y. Cherapanamjeri, B. Park, T. Naumann, A. Odisho, and B. Yu (2023). [Diagnosing transformers: illuminating feature space for clinical decison-making.](https://arxiv.org/abs/2305.17588) ICLR 2023. [https://arxiv.org/abs/2305.17588](https://arxiv.org/abs/2305.17588)
1. C. Singh, A. R. Hsu, R. Antonello, S. Jain, A. G. Huth, B. Yu and J. Gao (2023). [Explaining black box text modules in natural language with language models.](https://arxiv.org/abs/2305.09863)
1. N. Ghosh, S. Mei, and B. Yu (2022). [The three stages of dynamics in high-dimensional kernel methods.](https://arxiv.org/abs/2111.07167) Proc. ICLR, 2022. [https://arxiv.org/abs/2111.07167](https://arxiv.org/abs/2111.07167)
1. W. Ha, C. Singh, F. Lanusse, S. Upadhyayula, and B. Yu (2021). [Adaptive Wavelet Distillation from Neural Networks through Interpretation.](https://nips.cc/Conferences/2021/ScheduleMultitrack?event=28027) Proc. NeurIPS 2021. ([code](https://github.com/Yu-Group/adaptive-wavelets))
1. L. Reiger, J. W. Murdoch, S. Singh, B. Yu (2020). [Interpretations are Useful: Penalizing Explanations to Align Neural Networks with Prior Knowledge](https://proceedings.icml.cc/static/paper_files/icml/2020/992-Paper.pdf). ICML Proceedings. ([code](https://github.com/laura-rieger/deep-explanation-penalization))
1. C. Singh, W. Ha, F. Lanusse, V. Boehm , J. Liu, B. Yu (2020). [Transformation Importance with Applications to Cosmology](https://arxiv.org/pdf/2003.01926.pdf) ICLR Workshop paper. ([code](https://github.com/csinva/transformation-importance))
1. Y. Chen, R. Dwivedi, M. J. Wainwright and B. Yu (2020) [Fast Mixing of Metropolized Hamiltonian Monte Carlo: Benefits of Multi-Step Gradients,](https://www.jmlr.org/papers/volume21/19-441/19-441.pdf) JMLR, [https://arxiv.org/abs/1905.12247](https://arxiv.org/abs/1905.12247)
1. R. Dwivedi, Y. Chen, M. J. Wainwright and B. Yu (2019) [Log-concave Sampling: Metropolis Hastings Algorithms are Fast](http://jmlr.org/papers/v20/19-306.html) JMLR. [http://jmlr.org/papers/v20/19-306.html](http://jmlr.org/papers/v20/19-306.html)
1. Y. Chen, R. Dwivedi, M. J. Wainwright and B. Yu (2018) [Fast MCMC Algorithms on Polytopes](http://jmlr.org/papers/v19/18-158.html). JMLR. http://jmlr.org/papers/v19/18-158.html
1. Y. Chen, R. Abbasi-Asl, A. Bloniarz, M. Oliver, B. Willmore, J. Gallant*, and B. Yu* (2018) [The DeepTune framework for modeling and characterizing neurons in visual cortex area V4](https://www.biorxiv.org/content/10.1101/465534v1) https://www.biorxiv.org/content/10.1101/465534v1
1. K. Kumbier, S. Sumanta, J. B. Brown, S. Celniker, and B. Yu* (2018) [Refining interaction search through signed iterative Random Forests.](https://arxiv.org/abs/1810.07287) [https://arxiv.org/abs/1810.0728](https://arxiv.org/abs/1810.0728) (an enhanced version of [iRF](https://www.pnas.org/doi/10.1073/pnas.1711236115), PCS related)
1. J. Murdoch, P. Liu, and B. Yu (2018) [Beyond word importance: contextual decomposition to extract interactions from LSTMs.](https://arxiv.org/abs/1801.05453) Proc. ICLR 2018. [https://arxiv.org/abs/1705.07356](https://arxiv.org/abs/1705.07356) ([code](https://github.com/csinva/hierarchical-dnn-interpretations))
1. S. Kunzel, J. Sekhon, P. Bickel, and B. Yu* (2019) [Meta-learners for Estimating Heterogeneous Treatment Effects using Machine Learning,](https://www.pnas.org/content/116/10/4156) PNAS. 116 (10) 4156-4165. [https://arxiv.org/abs/1706.03461](https://arxiv.org/abs/1706.03461) ([code](https://github.com/soerenkuenzel/hte))
1. S. Basu, K. Kumbier, J. B. Brown*, and B. Yu* (2018) [iterative Random Forests to discover predictive and stable high-order interactions](https://www.stat.berkeley.edu/~binyu/ps/papers2018/iRF+SI18.pdf) PNAS, 115 (8), 1943-1948. ([code](https://github.com/Yu-Group/iterative-Random-Forest)) (PCS related)
1. S. Balakrishnan, M. Wainwright, B. Yu (2017) [Statistical Guarantees for the EM algorithm: from population to sample-based analysis.](https://www.stat.berkeley.edu/~binyu/ps/papers2017/EM17.pdf) Annals of Statistics, 45(1), 77 - 120.
1. S. Wu and B. Yu (2018). [Local identifiability of l1-minimization dictionary learning: a sufficient and almost necessary condition.](https://www.stat.berkeley.edu/~binyu/ps/papers2018/local-iden18.pdf) JMLR. 18, 1 - 56.
1. K. Rohe, T. Qin and B. Yu* (2016). [Co-clustering directed graphs to discover asymmetries and directional communities.](http://www.pnas.org/content/113/45/12679.full.pdf?with-ds=yes) Proc. National Academy of Sciences (PNAS), 113(45), 12679 - 12684.
1. Siqi Wu, Antony Joseph, Ann S. Hammonds, Susan E. Celniker, Bin Yu*, and Erwin Frise* (2016). [Stability-driven nonnegative matrix factorization to interpret spatial gene expression and build local gene networks (with support information).](https://www.stat.berkeley.edu/~binyu/ps/papers2016/staNMF+SI.pdf) PNAS, pp. 4290 - 4295. ([code](https://github.com/yu-group/stanmf)) (PCS related)
1. A. Bloniarz, H. Liu, C. Zhang, J. Sekhon, and B. Yu* (2015). [Lasso adjustments of treatment effect estimates in randomized experiments.](https://www.stat.berkeley.edu/~binyu/ps/papers2016/lasso-adj+SI16.pdf) PNAS. 113, 7383 - 7390.
