---
title: "Tree-based Methods"
---

[Complete Paper List in Reverse Chronological Order](../papers.qmd)

## Selected Recent Papers on Tree-based Methods

1. Y. S. Tan, O. Ronen, T. Saarinen, B. Yu (2024). [The Computational Curse of Big Data for Bayesian Additive Regression Trees: a Hitting Time Analysis.](https://arxiv.org/pdf/2406.19958)
1. Y. S. Tan, C. Singh, K. Nasseri, A. Agarwal, J. Duncan, O. Ronen, M. Epland, A. Kornblith, B. Yu (2022). [Fast interpretable greedy-tree sums (FIGS).](https://arxiv.org/abs/2201.11931) ([imodels 🔎: a python package for fitting interpretable models](https://github.com/csinva/imodels) contains code for FIGS).
1. M. Behr, Y. Wang, X. Li, B. Yu (2022). [Provable Boolean Interaction Recovery from Tree Ensemble obtained via Random Forests.](https://arxiv.org/abs/2102.11800) PNAS, (theory for a tractable version of [iRF](https://www.pnas.org/doi/10.1073/pnas.1711236115), PCS-related)
1. A. Agarwal, Y. S. Tan, O. Ronen, C. Singh, B. Yu (2022). [Hierarchical shrinkage: improving accuracy and interpretability of tree-based methods.](https://arxiv.org/abs/2202.00858) Proc. ICML ([imodels 🔎: a python package for fitting interpretable models](https://github.com/csinva/imodels) contains code for hierarchical shrinkage (HS))
1. Y. Tan, A. Agarwal, and B. Yu (2021). [A cautionary tale on fitting decision trees to data from additive models: generalization lower bounds.](https://arxiv.org/abs/2110.09626) Proc. AISTATS.
1. M. Behr*, K. Kumbier*, A. Cordova-Palomera, M. Aguirre, E. Ashley, A. Butte, R. Arnaout, J. B. Brown, J. Preist*, B. Yu* (2020). [Learning epistatic polygenic phenotypes with Boolean interactions.](https://www.biorxiv.org/content/10.1101/2020.11.24.396846v1) ([code](https://github.com/merlebehr/epiTree)) (PCS inference case study)
1. K. Kumbier, S. Sumanta, J. B. Brown, S. Celniker, and B. Yu* (2018) [Refining interaction search through signed iterative Random Forests.](https://arxiv.org/abs/1810.07287) (an enhanced version of [iRF](https://www.pnas.org/doi/10.1073/pnas.1711236115), PCS related)
1. S. Basu, K. Kumbier, J. B. Brown*, and B. Yu* (2018) [iterative Random Forests to discover predictive and stable high-order interactions](https://www.stat.berkeley.edu/~binyu/ps/papers2018/iRF+SI18.pdf) PNAS, 115 (8), 1943-1948. ([code](https://github.com/Yu-Group/iterative-Random-Forest)) (PCS related)
