---
title: "Veridical Data Science (PCS)"
---

[Complete Paper List in Reverse Chronological Order](../papers.qmd)

## Selected Recent Papers on Veridical Data Science (PCS)

1. B. Yu (2024). [After Computational Reproducibility: Scientific Reproducibility and Trustworthy AI](https://hdsr.mitpress.mit.edu/pub/8qexde24/release/1) (discussion of Donoho's paper "Data Science at the Singularity") Harvard Data Science Review (HDSR).
1. B. Yu (2023). [What is uncertainty in today's practice of data science?](https://www.sciencedirect.com/science/article/abs/pii/S030440762300235X?dgcid=author) J. Econometrics. 237, 105519.
1. Q. Wang, T. M. Tang, N. Youlton, C. S. Weldy, A. M. Kenney, O. Ronen, J. W. Hughes, E. T. Chin, S. C. Sutton. A. Agarwal, X. Li, M. Behr, K. Kumbier, C. S. Moravec, W. H. W. Tang, K. B. Margulies, T. P. Cappola, A. J. Buitte, R. Arnaout, J. B. Brown, J. R. Priest, V. N. Parikh, B. Yu, E. Ashley (2023). [Epistasis regulates genetic control of cardiac hypertrophy.](https://www.medrxiv.org/content/10.1101/2023.11.06.23297858v1) ([Code](https://github.com/Yu-Group/epistasis-cardiac-hypertrophy)) ([PCS documentation](https://yu-group.github.io/epistasis-cardiac-hypertrophy/#overview))
1. R. Cahill, Y. Wang, R. P. Xian, A. J. Lee, H. Zeng, B. Yu, B. Tasic, R. Abbasi-Asl (2023). [Unsupervised pattern discovery in spatial gene expression atlas reveals mouse brain regions beyond established ontology.](https://www.biorxiv.org/content/10.1101/2023.03.10.531984v2) ([Code](https://github.com/abbasilab/osNMF))
1. A. Agarwal, A. M. Kenny, Y. S. Tan, T. M. Tang, B. Yu (2023). [MDI+: a flexible random forest-based feature importance framework.](https://arxiv.org/abs/2307.01932) (PCS related)
1. M. Behr*, K. Kumbier*, A. Cordova-Palomera, M. Aguirre, E. Ashley, A. Butte, R. Arnaout, J. B. Brown, J. Preist*, B. Yu* (2020). [Learning epistatic polygenic phenotypes with Boolean interactions.](https://www.biorxiv.org/content/10.1101/2020.11.24.396846v1) ([code](https://github.com/merlebehr/epiTree)) (PCS inference case study)
1. B. Norgeot*, G. Quer, B. K. Beaulieu-Jones, A. Torkamani, R. Dias, M. Gianfrancesco, R. Arnaout, I. S. Kohane, S. Saria, E. Topol, Z. Obermeyer, B. Yu & A. Butte* (2020). [Minimum information about clinical artificial intelligence modeling: the MI-CLAIM checklist](https://www.nature.com/articles/s41591-020-1041-y), Nature Medicine, 26, 1320–1324.
1. B. Yu (2020). [Stability expanded, in reality](https://hdsr.mitpress.mit.edu/pub/ekrhsui8/release/1). Harvard Data Science Review (HDSR). (PCS related)
1. B. Yu and R. Barter (2020). [Data science process: one culture.](https://www.tandfonline.com/doi/abs/10.1080/01621459.2020.1762615?journalCode=uasa20) JASA. (PCS related)
1. R. Dwivedi*, Y. Tan*, B. Park, M. Wei, K. Horgan, D. Madigan*, B. Yu* (2020). [Stable discovery of interpretable subgroups via calibration in causal studies (staDISC).](https://onlinelibrary.wiley.com/doi/10.1111/insr.12427) International Statistical Review ([arXiv](https://arxiv.org/abs/2008.10109)) ([code](https://github.com/Yu-Group/stadisc)) (PCS case study for causal inference)
1. X. Li, T. M. Tang, X. Wang, J. A. Kocher, B. Yu (2020). [A stability-driven protocol for drug response interpretable prediction (staDRIP)](https://arxiv.org/abs/2011.06593). NeurISP workshop on ML4H (Machine learning for Health) Extended Abstract. [drive link](https://drive.google.com/file/d/1QwQwQwQwQwQwQwQwQwQwQwQwQwQwQwQ/view)
1. B. Yu and K. Kumbier (2020) [Veridical data science](https://www.stat.berkeley.edu/~binyu/ps/papers2020/VDS20-YuKumbier.pdf) (PCS framework), PNAS. 117 (8), 3920-3929. [QnAs with Bin Yu.](https://www.stat.berkeley.edu/~binyu/ps/papers2020/VDS20-QnAsBinYu.pdf)
1. Y. Chen, R. Abbasi-Asl, A. Bloniarz, M. Oliver, B. Willmore, J. Gallant*, and B. Yu* (2018) [The DeepTune framework for modeling and characterizing neurons in visual cortex area V4.](https://www.biorxiv.org/content/10.1101/465534v1)
1. K. Kumbier, S. Sumanta, J. B. Brown, S. Celniker, and B. Yu* (2018) [Refining interaction search through signed iterative Random Forests.](https://arxiv.org/abs/1810.07287) (an enhanced version of [iRF](https://www.pnas.org/doi/10.1073/pnas.1711236115), PCS related)
1. S. Basu, K. Kumbier, J. B. Brown*, and B. Yu* (2018) [iterative Random Forests to discover predictive and stable high-order interactions](https://www.stat.berkeley.edu/~binyu/ps/papers2018/iRF+SI18.pdf) PNAS, 115 (8), 1943-1948. ([code](https://github.com/Yu-Group/iterative-Random-Forest)) (PCS related)
1. Siqi Wu, Antony Joseph, Ann S. Hammonds, Susan E. Celniker, Bin Yu*, and Erwin Frise* (2016). [Stability-driven nonnegative matrix factorization to interpret spatial gene expression and build local gene networks (with support information).](https://www.stat.berkeley.edu/~binyu/ps/papers2016/staNMF+SI.pdf) PNAS, pp. 4290 - 4295. ([code](https://github.com/yu-group/stanmf)) (PCS related)
